name: Build release

on:
  schedule:
    # Runs "At 11:00 on every day-of-week from Monday through Friday"
    - cron: '0 */1 * * *'
  push:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add SHORT_SHA env property with commit short sha
        run: |
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
          echo "TAG=version_$SHORT_SHA" >> $GITHUB_ENV

      - name: Build app
        run: |
          echo "#!/bin/bash" >> runme-${GITHUB_SHA}.sh
          echo "am app" >> runme-${GITHUB_SHA}.sh
          echo "it's $(date +"%D - %H:%M:%S")" >> runme-${GITHUB_SHA}.sh


      - uses: avakar/tag-and-release@v1
        with:
          tag_name: ${{ env.TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   # if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     name: version_${GITHUB_SHA}
      #     files: runme-${GITHUB_SHA}.sh
