name: Build release

on:
  schedule:
    # Runs "At 11:00 on every day-of-week from Monday through Friday"
    - cron: '0 */1 * * *'
  push:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}

      - name: Build app
        run: |
          echo "#!/bin/bash" >> runme-${{ steps.vars.outputs.sha_short }}.sh
          echo "am app" >> runme-${{ steps.vars.outputs.sha_short }}.sh
          echo "it's $(date +"%D - %H:%M:%S")" >> runme-${{ steps.vars.outputs.sha_short }}.sh


      - uses: avakar/tag-and-release@v1
        with:
          tag_name: v_${{ steps.vars.outputs.sha_short }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: version_${{ steps.vars.outputs.sha_short }}
          files: runme-${{ steps.vars.outputs.sha_short }}.sh
