name: Build release

on:
  schedule:
    - cron: '* * * * * *'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build app
        run: |
          echo "#!/bin/bash" >> runme.sh
          echo "am app" >> runme.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: runme.sh
