name: Build release

on:
  schedule:
    # Runs "At 11:00 on every day-of-week from Monday through Friday"
    - cron: '0 */1 * * *'
  push:


jobs:
  build-it:
    runs-on: ubuntu-latest
    container:
      image: legleux/amm-builder
      volumes:
        - $PWD/rippled:/rippled
    #   options: --cpus 1
    # steps:
    #   - name: Check for dockerenv file
    #     run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set outputs
        id: vars
        run: |
          GIT_REV=$(git rev-parse --short HEAD)
          echo "::set-output name=sha_short::${GIT_REV}"
          TIME=$(date +"%Y-%m-%d-%H_%M_%S")
          echo "::set-output name=release_time::${TIME}"
          echo "::set-output name=tag_name::version_${TIME}"
      - name: Check outputs
        run: |
          echo ${{ steps.vars.outputs.sha_short }}
          echo ${{ steps.vars.outputs.release_time }}
          echo ${{ steps.vars.outputs.tag_name }}

      # - name: Build app
      #   run: |
      #     FILE=runme-${{ steps.vars.outputs.sha_short }}.sh
      #     echo "#!/bin/bash" >> $FILE
      #     echo "echo \"It's ${{ steps.vars.outputs.release_time }}\"" >> $FILE

      - name: Build
        run: |
          git clone --depth 1 --branch "amm-core-functionality" "https://github.com/gregtatcam/rippled.git"
          echo "***in gh***"
          echo $PWD
          ls -lah
          echo "***********"
          docker run -v $PWD:/rippled legleux/amm-builder

      - uses: avakar/tag-and-release@v1
        with:
          tag_name: ${{ steps.vars.outputs.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: "Version ${{ steps.vars.outputs.sha_short }}"
          tag_name: ${{ steps.vars.outputs.tag_name }}
          files: rippled/build/rippled
